name: apptravella
description: "A travel booking application built with Flutter."
publish_to: 'none'

version: 1.0.0+1

environment:
  # نطاق SDK الخاص بك، تأكد من أنه يشمل 3.5.4
  # قد تحتاج لتعديله قليلاً إذا كان يقيد استخدام إصدارات أقدم من الحزم
  sdk: '>=3.1.0 <4.0.0' # هذا النطاق جيد ويشمل 3.5.4
dependencies:
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.8
  table_calendar: ^3.2.0
  country_picker: 2.0.27
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  responsive_framework: ^1.1.0
  

  # State Management
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  provider: ^6.1.4

  # Network & API
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  internet_connection_checker: ^3.0.1

  # Local Storage
  shared_preferences: ^2.5.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Utils
  intl: 0.20.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^8.0.3
  google_maps_flutter: ^2.12.1
  image_picker: ^1.1.2
  flutter_stripe: ^11.5.0
  url_launcher: ^6.3.1
  signalr_netcore: ^1.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/
   
    # - assets/hurghada/
    # - assets/giza/
    # - assets/sharm/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
# name: travella
# description: "A travel booking application built with Flutter." # Descriptive name
# publish_to: 'none' # Prevents accidental publishing to pub.dev

# version: 1.0.0+1

# environment:
#   # Using a common stable SDK range. Adjust if you need specific features from newer SDKs.
#   sdk: '>=3.1.0 <4.0.0'

# dependencies:
#   flutter:
#     sdk: flutter

#   # Core UI & Icons - Usually included
#   cupertino_icons: ^1.0.6 # Using caret for latest patch/minor compatible version

#   # State Management
#   provider: ^6.1.2 # Using caret for latest stable compatible version

#   # Utilities & Features
#   intl: ^0.19.0         # Date/Number formatting (using caret)
#   shared_preferences: ^2.2.2 # Local storage (using caret)
#   country_picker: ^2.0.25   # Country selection UI (using caret)
#   table_calendar: ^3.1.1   # Calendar UI (using caret)

# dev_dependencies:
#   flutter_test:
#     sdk: flutter

#   # Recommended linters for code analysis - update to latest stable
#   flutter_lints: ^3.0.1 # Using caret for latest stable compatible version

# # Flutter specific configurations
# flutter:
#   uses-material-design: true

#   # Asset Management
#   # Make sure you have an 'assets' folder in the root of your project.
#   # Including the directory path includes all files within it.
#   assets:
#     - assets/ # This line includes logo.jpeg, onboarding3.jpeg, and any other file in assets/

#   # If you had fonts, they would go here:
#   # fonts:
#   #   - family: Schyler
#   #     fonts:
#   #       - asset: fonts/Schyler-Regular.ttf
#   #       - asset: fonts/Schyler-Italic.ttf
#   #         style: italic
#   #   - family: Trajan Pro
#   #     fonts:
#   #       - asset: fonts/TrajanPro.ttf
#   #       - asset: fonts/TrajanPro_Bold.ttf
#   #         weight: 700